package com.m2i.charron.web.gamefarm.Hibernate;
// Generated 6 avr. 2018 14:38:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Joueur generated by hbm2java
 */
public class Joueur  implements java.io.Serializable {


     private Integer id;
     private String pseudo;
     private Set<Exploitation> exploitations = new HashSet<Exploitation>(0);
     private Set<Refressours> refressourses = new HashSet<Refressours>(0);
     private Set<Refjoueur> refjoueurs = new HashSet<Refjoueur>(0);

    public Joueur() {
    }

	
    public Joueur(String pseudo) {
        this.pseudo = pseudo;
    }
    public Joueur(String pseudo, Set<Exploitation> exploitations, Set<Refressours> refressourses, Set<Refjoueur> refjoueurs) {
       this.pseudo = pseudo;
       this.exploitations = exploitations;
       this.refressourses = refressourses;
       this.refjoueurs = refjoueurs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }
    public Set<Exploitation> getExploitations() {
        return this.exploitations;
    }
    
    public void setExploitations(Set<Exploitation> exploitations) {
        this.exploitations = exploitations;
    }
    public Set<Refressours> getRefressourses() {
        return this.refressourses;
    }
    
    public void setRefressourses(Set<Refressours> refressourses) {
        this.refressourses = refressourses;
    }
    public Set<Refjoueur> getRefjoueurs() {
        return this.refjoueurs;
    }
    
    public void setRefjoueurs(Set<Refjoueur> refjoueurs) {
        this.refjoueurs = refjoueurs;
    }




}


