package com.m2i.charron.web.gamefarm.Hibernate;
// Generated 6 avr. 2018 14:38:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partie generated by hbm2java
 */
public class Partie  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Date date;
     private Set<Refressours> refressourses = new HashSet<Refressours>(0);
     private Set<Exploitation> exploitations = new HashSet<Exploitation>(0);
     private Set<Refjoueur> refjoueurs = new HashSet<Refjoueur>(0);

    public Partie() {
    }

	
    public Partie(String nom, Date date) {
        this.nom = nom;
        this.date = date;
    }
    public Partie(String nom, Date date, Set<Refressours> refressourses, Set<Exploitation> exploitations, Set<Refjoueur> refjoueurs) {
       this.nom = nom;
       this.date = date;
       this.refressourses = refressourses;
       this.exploitations = exploitations;
       this.refjoueurs = refjoueurs;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Refressours> getRefressourses() {
        return this.refressourses;
    }
    
    public void setRefressourses(Set<Refressours> refressourses) {
        this.refressourses = refressourses;
    }
    public Set<Exploitation> getExploitations() {
        return this.exploitations;
    }
    
    public void setExploitations(Set<Exploitation> exploitations) {
        this.exploitations = exploitations;
    }
    public Set<Refjoueur> getRefjoueurs() {
        return this.refjoueurs;
    }
    
    public void setRefjoueurs(Set<Refjoueur> refjoueurs) {
        this.refjoueurs = refjoueurs;
    }




}


