package com.m2i.charron.web.gamefarm.Hibernate;
// Generated 6 avr. 2018 14:38:30 by Hibernate Tools 4.3.1



/**
 * Refjoueur generated by hbm2java
 */
public class Refjoueur  implements java.io.Serializable {


     private RefjoueurId id;
     private Joueur joueur;
     private Partie partie;

    public Refjoueur() {
    }

    public Refjoueur(RefjoueurId id, Joueur joueur, Partie partie) {
       this.id = id;
       this.joueur = joueur;
       this.partie = partie;
    }
   
    public RefjoueurId getId() {
        return this.id;
    }
    
    public void setId(RefjoueurId id) {
        this.id = id;
    }
    public Joueur getJoueur() {
        return this.joueur;
    }
    
    public void setJoueur(Joueur joueur) {
        this.joueur = joueur;
    }
    public Partie getPartie() {
        return this.partie;
    }
    
    public void setPartie(Partie partie) {
        this.partie = partie;
    }




}


