package com.m2i.charron.web.gamefarm.Hibernate;
// Generated 6 avr. 2018 14:38:30 by Hibernate Tools 4.3.1



/**
 * Refressours generated by hbm2java
 */
public class Refressours  implements java.io.Serializable {


     private Integer id;
     private Joueur joueur;
     private Partie partie;
     private Typeressource typeressource;
     private int qtR;

    public Refressours() {
    }

    public Refressours(Joueur joueur, Partie partie, Typeressource typeressource, int qtR) {
       this.joueur = joueur;
       this.partie = partie;
       this.typeressource = typeressource;
       this.qtR = qtR;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Joueur getJoueur() {
        return this.joueur;
    }
    
    public void setJoueur(Joueur joueur) {
        this.joueur = joueur;
    }
    public Partie getPartie() {
        return this.partie;
    }
    
    public void setPartie(Partie partie) {
        this.partie = partie;
    }
    public Typeressource getTyperessource() {
        return this.typeressource;
    }
    
    public void setTyperessource(Typeressource typeressource) {
        this.typeressource = typeressource;
    }
    public int getQtR() {
        return this.qtR;
    }
    
    public void setQtR(int qtR) {
        this.qtR = qtR;
    }




}


