package com.m2i.charron.web.gamefarm.Hibernate;
// Generated 6 avr. 2018 14:38:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typeressource generated by hbm2java
 */
public class Typeressource  implements java.io.Serializable {


     private Integer idtr;
     private String libelle;
     private Integer type;
     private Set<Refressours> refressourses = new HashSet<Refressours>(0);
     private Set<Exploitation> exploitations = new HashSet<Exploitation>(0);

    public Typeressource() {
    }

    public Typeressource(String libelle, Integer type, Set<Refressours> refressourses, Set<Exploitation> exploitations) {
       this.libelle = libelle;
       this.type = type;
       this.refressourses = refressourses;
       this.exploitations = exploitations;
    }
   
    public Integer getIdtr() {
        return this.idtr;
    }
    
    public void setIdtr(Integer idtr) {
        this.idtr = idtr;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Set<Refressours> getRefressourses() {
        return this.refressourses;
    }
    
    public void setRefressourses(Set<Refressours> refressourses) {
        this.refressourses = refressourses;
    }
    public Set<Exploitation> getExploitations() {
        return this.exploitations;
    }
    
    public void setExploitations(Set<Exploitation> exploitations) {
        this.exploitations = exploitations;
    }




}


